# Practical_6: Numpy

In [225]:
import numpy as np

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

```python

```

In [14]:

a = np.arange(1,11)
print(a)


[ 1  2  3  4  5  6  7  8  9 10]


---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.



In [6]:
help (np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this arg

In [12]:
b = (3,3)
np.zeros(b, dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])



### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.



In [19]:
c = np.linspace(0,5,10, endpoint=False)
print(c)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


### Exercise 4:
Create a 5x5 identity matrix using NumPy.

```python
# Exercise 4
```

---

In [20]:
d = np.eye(5)
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

```python
# Exercise 5
```

---

In [22]:
e = np.random.rand(4,4)
e

array([[0.03230999, 0.38933843, 0.17799591, 0.19113217],
       [0.47980569, 0.34094669, 0.22885364, 0.80780289],
       [0.97339813, 0.10204151, 0.30454627, 0.78789526],
       [0.93414226, 0.65390147, 0.19232257, 0.68275108]])

### Exercise 6:
Find the shape of a NumPy array.

```python
# Exercise 6


In [47]:
A = np.arange(1, 10).reshape((3, 3))
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7
```

---

In [48]:
A = np.arange(16)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [49]:
A = np.arange(16).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### Exercise 8:
Find the data type of the elements in a NumPy array.

```python
# Exercise 8


In [ ]:
A= np

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python
# Exercise 9
```

---

In [30]:
A=[x for x in np. arange(1,101) if x % 2 == 0]
A

[2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100]

In [32]:
A = np.arange(2,101,2)
A

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python
# Exercise 10
```

---

In [40]:
A = np.random.randint(10,50,(6,6))
A

array([[30, 26, 17, 29, 25, 20],
       [41, 20, 46, 12, 14, 44],
       [23, 15, 27, 41, 28, 15],
       [24, 15, 12, 18, 14, 28],
       [28, 45, 17, 49, 18, 41],
       [49, 49, 27, 10, 16, 18]])

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python


In [64]:
A = np.array(np.mat('1 2; 3 4'))
A

array([[1, 2],
       [3, 4]])

In [55]:
help (np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

### Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python
# Exercise 12


In [69]:
A = np.array([[2,4,6], [1,2,3]])
print(np.sum(A))


18


### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.



In [72]:
A = np.array([[2,4,6], [1,2,3]])
print(np.mean(A))
print(np.median(A))
print(np.std(A))

3.0
2.5
1.632993161855452


### Exercise 14:
Find the maximum and minimum values in a NumPy array.



In [73]:
A = np.array([[2,4,6], [1,2,3]])
print(np.min(A))
print(np.max(A))

1
6


### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.



In [211]:
A = np.random.rand(20)
max_index = np.argmax(A) 
print(max_index)


17


### Exercise 16:
Create a NumPy array and reverse its elements.

In [213]:
A = np.array([[1,2,3], [4,5,6]])
res = np.flip(A)
print(A)
print(res)

[[1 2 3]
 [4 5 6]]
[[6 5 4]
 [3 2 1]]


### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

In [228]:
A = np.arange(1, 10).reshape((3, 3))
print(A*A)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


### Exercise 18:
Create a diagonal matrix from a given 1D array.

In [230]:
A = np.diag([1,2,3])
A

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

In [235]:
A = np.arange(1,5).reshape(2,2)
B = np.arange(6,10).reshape(2,2)
print(A*B)

[[ 6 14]
 [24 36]]


### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

In [237]:
A = np.arange(1,5).reshape(2,2)
B = np.arange(6,10).reshape(2,2)
print(A)
print(B)

[[1 2]
 [3 4]]
[[6 7]
 [8 9]]


### Exercise 21:
Stack two NumPy arrays vertically.

In [239]:
A = np.arange(1,5).reshape(2,2)
B = np.arange(6,10).reshape(2,2)
C = np.vstack((A,B))
print(C)

[[1 2]
 [3 4]
 [6 7]
 [8 9]]


### Exercise 22:
Stack two NumPy arrays horizontally.

In [240]:
A = np.arange(1,5).reshape(2,2)
B = np.arange(6,10).reshape(2,2)
C = np.hstack((A,B))
print(C)

[[1 2 6 7]
 [3 4 8 9]]


### Exercise 23:
Split a NumPy array into multiple sub-arrays.

In [252]:
A = np.array([1,2,3,5,6])
B = np.split(A,[1,2])
B



[array([1]), array([2]), array([3, 5, 6])]

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

In [269]:
A = np.random.rand(6)
np.around(A,decimals = 2)


array([0.43, 0.67, 0.54, 0.29, 0.09, 0.82])

### Exercise 25:
Find the unique elements of a NumPy array.

In [272]:
A = np.array([1,5,5,7,8,8])
np.unique(A)


array([1, 5, 7, 8])

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

```python
# Exercise 26
```

---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

```python
# Exercise 27
```

---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

```python
# Exercise 28
```

---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

```python
# Exercise 29
```

---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

```python
# Exercise 30
```

---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

```python
# Exercise 31
```

---

### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
# Exercise 32
```

---

### Exercise 33:
Find the trace of a square NumPy matrix.

```python
# Exercise 33
```

---

### Exercise 34:
Create a 2D array and swap two rows.

```python
# Exercise 34
```

---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python
# Exercise 35
```

---

### Exercise 36:
Find the determinant of a 3x3 matrix.

```python
# Exercise 36
```

---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python
# Exercise 37
```

---

### Exercise 38:
Solve a system of linear equations using NumPy.

```python
# Exercise 38
```

---

### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python
# Exercise 40
```

---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---